name: Publish to GitHub Packages

on:
  push:
    branches:
      - master
  #  release:
  #   types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
      - name: Call my Gradle Task
        run: ./gradlew publish -DREPOSILITE_USER=${{ secrets.REPOSILITE_USER }} -DREPOSILITE_TOKEN=${{ secrets.REPOSILITE_TOKEN }}